# Generated by Django 5.2.13 on 2026-04-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/%Y/%m/", verbose_name="Файл"),
        ),
    ]
