# Generated by Django 5.2.13 on 2026-05-02 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_alter_document_file"),
        ("properties", "0003_alter_apartment_id_alter_building_id"),
        ("residents", "0007_alter_resident_tc_kimlik_no_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("building__isnull", False),
                    ("apartment__isnull", False),
                    ("resident__isnull", False),
                    _connector="OR",
                ),
                name="document_has_at_least_one_link",
            ),
        ),
    ]
