version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/crm_backend/requirements"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Nazarovruslan01"
    labels:
      - "dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "Nazarovruslan01"
    labels:
      - "ci/cd"
