# Generated by Django 5.2.13 on 2026-04-23 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("plumbing", "Tesisat"),
                            ("electrical", "Elektrik"),
                            ("cleaning", "Temizlik"),
                            ("security", "Güvenlik"),
                            ("noise", "Gürültü"),
                            ("general", "Genel"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Düşük"), ("medium", "Normal"), ("high", "Yüksek"), ("urgent", "Acil")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yeni"),
                            ("assigned", "Atandı"),
                            ("in_progress", "İşlemde"),
                            ("resolved", "Çözüldü"),
                            ("closed", "Kapatıldı"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("photo_urls", models.JSONField(blank=True, default=list, help_text="Array of photo URLs")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tickets", to="properties.apartment"
                    ),
                ),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to="staff.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_url", models.URLField(max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="tickets.ticket"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Attachment",
                "verbose_name_plural": "Ticket Attachments",
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("photo_urls", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="tickets.ticket"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Comment",
                "verbose_name_plural": "Ticket Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["apartment"], name="tickets_tic_apartme_f1423c_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="tickets_tic_status_0e5646_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["priority"], name="tickets_tic_priorit_0bec9b_idx"),
        ),
    ]
