# Generated by Django 5.2.13 on 2026-04-26 15:27

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_ticket_tickets_tic_apartme_54f61b_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketattachment",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Ticket Attachment",
                "verbose_name_plural": "Ticket Attachments",
            },
        ),
        migrations.AlterField(
            model_name="ticket",
            name="photo_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of photo URLs",
                validators=[core.validators.validate_photo_urls],
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="photo_urls",
            field=models.JSONField(blank=True, default=list, validators=[core.validators.validate_photo_urls]),
        ),
    ]
