# Generated by Django 5.2.13 on 2026-04-24 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_add_performance_indexes"),
        ("tickets", "0002_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["ticket"], name="staff_task_ticket__8e0116_idx"),
        ),
    ]
