# Generated by Django 5.2.13 on 2026-04-26 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_task_staff_task_ticket__8e0116_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["name"], "verbose_name": "Department", "verbose_name_plural": "Departments"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["-created_at"], "verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
    ]
