# Generated by Django 5.2.13 on 2026-04-23 16:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Site/Complex Name")),
                ("address", models.TextField(verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("district", models.CharField(max_length=100, verbose_name="District")),
                (
                    "management_type",
                    models.CharField(
                        choices=[("self_managed", "Kendi Yönetim"), ("external_company", "Dış Yönetim Şirketi")],
                        default="self_managed",
                        max_length=20,
                    ),
                ),
                (
                    "annual_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Annual Budget (TRY)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("apartment_number", models.CharField(max_length=20)),
                ("floor", models.PositiveIntegerField(blank=True, null=True)),
                ("block", models.CharField(blank=True, max_length=10, verbose_name="Block (Blok)")),
                (
                    "square_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Square Meters (m²)"
                    ),
                ),
                (
                    "share_ratio_num",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Numerator (pay)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "share_ratio_denom",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Denominator (payda)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "tapu_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, unique=True, verbose_name="TAPU Number (Tapu Sicil No)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending_handover", "Teslim Bekliyor"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="properties.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartment",
                "verbose_name_plural": "Apartments",
                "ordering": ["building", "block", "apartment_number"],
                "unique_together": {("building", "apartment_number")},
            },
        ),
    ]
