# Generated by Django 5.2.13 on 2026-05-12 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_apartment_id_alter_building_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users with manager role who manage this building",
                related_name="managed_buildings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Managers",
            ),
        ),
    ]
