# Generated by Django 5.2.13 on 2026-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_aidatcharge_unique_aidat_per_apartment_period"),
        ("properties", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Client-generated key to prevent duplicate payments on retries.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["idempotency_key"], name="billing_pay_idempot_96c174_idx"),
        ),
    ]
