# Generated by Django 5.2.13 on 2026-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_add_payment_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
