# Generated by Django 5.2.13 on 2026-04-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_alter_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraordinarycharge",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
