# Generated by Django 5.2.13 on 2026-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_alter_receipt_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="charge_type",
            field=models.CharField(
                choices=[("aidat", "Aidat"), ("extraordinary", "Olağanüstü Aidat"), ("other", "Diğer")],
                help_text="Type of charge being paid",
                max_length=20,
            ),
        ),
    ]
