# Generated by Django 5.2.13 on 2026-04-26 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_payment_charge_type_choices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extraordinarycharge",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Extraordinary Charge",
                "verbose_name_plural": "Extraordinary Charges",
            },
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={"ordering": ["-generated_at"], "verbose_name": "Receipt", "verbose_name_plural": "Receipts"},
        ),
    ]
