# Generated by Django 5.2.13 on 2026-04-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_add_model_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='iyzico_conversation_id',
            field=models.CharField(blank=True, help_text='İyzico conversationId returned in checkout form init', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='iyzico_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='İyzico paymentId (e.g. 123456789)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='iyzico_token',
            field=models.CharField(blank=True, help_text='İyzico token returned in callback', max_length=255, null=True),
        ),
    ]
