# Generated by Django 5.2.13 on 2026-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_alter_aidatcharge_apartment_alter_payment_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="iyzico_conversation_id",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Iyzico Conversation ID"),
        ),
        migrations.AddField(
            model_name="payment",
            name="iyzico_payment_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, verbose_name="Iyzico Payment ID"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="iyzico_token",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Iyzico Checkout Token"),
        ),
    ]
