# Generated by Django 5.2.13 on 2026-05-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_add_iyzico_fields_to_payment"),
        ("properties", "0003_alter_apartment_id_alter_building_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="aidatcharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("late_fee_rate__gte", 0), ("late_fee_rate__lte", 0.5)),
                name="late_fee_rate_bounds",
                violation_error_message="Late fee rate must be between 0 and 0.5 (50%).",
            ),
        ),
    ]
