# Generated by Django 5.2.13 on 2026-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0012_add_late_fee_rate_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Bekliyor"),
                    ("completed", "Tamamlandı"),
                    ("failed", "Başarısız"),
                    ("refunded", "İade Edildi"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
