# Generated by Django 5.2.13 on 2026-05-12 17:18
# Rewritten: 0001_initial created charge_id as UUIDField. On a fresh database
# the original AlterField tried `USING "charge_id"::bigint` which psycopg2
# rejects (no implicit cast from uuid to bigint). Use explicit USING NULL since
# the column is nullable and on fresh databases contains no data.
# RunPython guards the SQL to PostgreSQL only — SQLite doesn't support this
# ALTER COLUMN syntax and has flexible typing anyway.

from django.db import migrations, models


def alter_charge_id_type(_apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute('ALTER TABLE "billing_payment" ALTER COLUMN "charge_id" TYPE bigint USING NULL;')


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_add_payment_status"),
    ]

    operations = [
        migrations.RunPython(
            alter_charge_id_type,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="payment",
                    name="charge_id",
                    field=models.BigIntegerField(
                        blank=True,
                        help_text="ID of the charge being paid (AidatCharge, ExtraordinaryCharge, etc.)",
                        null=True,
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
