# Generated by Django 5.2.13 on 2026-05-12 17:18
# Rewritten: 0001_initial created charge_id as UUIDField. On a fresh database
# the original AlterField tried `USING "charge_id"::bigint` which psycopg2
# rejects (no implicit cast from uuid to bigint). Use RunSQL with an explicit
# USING NULL since the column is nullable and on fresh databases contains no
# data. On environments that already applied the original migration the
# column is already BigIntegerField, so the cast is a no-op. The state
# operation keeps Django's view of the schema in sync.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_add_payment_status"),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "billing_payment" ALTER COLUMN "charge_id" TYPE bigint USING NULL;',
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name="payment",
                    name="charge_id",
                    field=models.BigIntegerField(
                        blank=True,
                        help_text="ID of the charge being paid (AidatCharge, ExtraordinaryCharge, etc.)",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
