# Generated by Django 5.2.13 on 2026-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_add_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="charge_id",
            field=models.BigIntegerField(
                blank=True, help_text="ID of the charge being paid (AidatCharge, ExtraordinaryCharge, etc.)", null=True
            ),
        ),
    ]
