# Generated by Django 5.2.13 on 2026-05-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0014_alter_payment_charge_id_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="iyzico_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name="Iyzico Checkout Token"
            ),
        ),
    ]
