# Generated by Django 5.2.13 on 2026-05-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_add_iyzico_token_index_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
