# Generated by Django 5.2.13 on 2026-05-13 07:24
# Purpose: Backfill payment.status for old payments created before 0013.
# Payments with a linked receipt (or receipt_number) are considered completed.

from django.db import migrations


def backfill_payment_status(apps, schema_editor):
    Payment = apps.get_model("billing", "Payment")
    Payment.objects.filter(
        status="pending",
        receipt__isnull=False,
    ).update(status="completed")
    # Also handle payments with receipt_number but no receipt object yet
    Payment.objects.filter(
        status="pending",
        receipt_number__isnull=False,
    ).exclude(receipt_number="").update(status="completed")


def revert_backfill(apps, schema_editor):
    # Reverting is intentionally a no-op; we cannot know previous state.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0016_receipt_pdf_url_nullable"),
    ]

    operations = [
        migrations.RunPython(backfill_payment_status, revert_backfill),
    ]
