# Generated by Django 5.2.14 on 2026-06-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0018_payment_amount_positive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="iyzico_conversation_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, verbose_name="Iyzico Conversation ID"
            ),
        ),
    ]
