# Production-safe index creation on billing_payment.iyzico_conversation_id.
#
# Django's ``AlterField(db_index=True)`` emits ``CREATE INDEX`` (SHARE lock)
# inside a transaction. On a large table that blocks writes for the duration
# of index build. Instead we create the index ``CONCURRENTLY`` (no write
# lock) and use ``SeparateDatabaseAndState`` so Django records the model
# state change without emitting a second duplicate ``CREATE INDEX``.
#
# ``atomic = False`` is required because ``CREATE INDEX CONCURRENTLY``
# cannot run inside a transaction.
#
# The ``IF NOT EXISTS`` / ``IF EXISTS`` guards make the migration re-entrant
# after a partial failure (the CONCURRENTLY operation commits immediately
# and cannot be rolled back).

# Generated by Django 5.2.14 on 2026-06-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0018_payment_amount_positive"),
    ]
    atomic = False

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="payment",
                    name="iyzico_conversation_id",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="Iyzico Conversation ID",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    "CREATE INDEX CONCURRENTLY IF NOT EXISTS payment_iyzico_conversation_id_idx"
                    " ON billing_payment (iyzico_conversation_id);",
                    reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS payment_iyzico_conversation_id_idx;",
                ),
            ],
        )
    ]
