# Production-safe index creation on billing_payment.iyzico_conversation_id.
#
# Django's AlterField(db_index=True) emits CREATE INDEX (SHARE lock) inside a
# transaction. On a large table that blocks writes. Instead we create the index
# CONCURRENTLY (no write lock) via RunPython guarded by a vendor check —
# SQLite doesn't support CONCURRENTLY / IF NOT EXISTS syntax.
#
# atomic = False is required because CREATE INDEX CONCURRENTLY cannot run
# inside a transaction.

# Generated by Django 5.2.14 on 2026-06-08 06:32

from django.db import migrations, models


def create_index(_apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS payment_iyzico_conversation_id_idx"
            " ON billing_payment (iyzico_conversation_id);"
        )


def drop_index(_apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX CONCURRENTLY IF EXISTS payment_iyzico_conversation_id_idx;")


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0018_payment_amount_positive"),
    ]
    atomic = False

    operations = [
        migrations.RunPython(create_index, reverse_code=drop_index),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="payment",
                    name="iyzico_conversation_id",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="Iyzico Conversation ID",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
