# Generated by Django 5.2.13 on 2026-04-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('aidat_reminder', 'Aidat Hatırlatma'), ('aidat_overdue', 'Aidat Gecikme'), ('payment_confirmation', 'Ödeme Onayı'), ('ticket_created', 'Talep Oluşturuldu'), ('ticket_assigned', 'Talep Atandı'), ('ticket_resolved', 'Talep Çözüldü'), ('meeting_reminder', 'Toplantı Hatırlatma'), ('general', 'Genel')], max_length=30)),
                ('channel', models.CharField(choices=[('push', 'Push Bildirim'), ('sms', 'SMS'), ('email', 'E-posta'), ('telegram', 'Telegram')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_template', models.TextField(help_text='Template with {name}, {apartment}, {amount}, etc.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('sent', 'Gönderildi'), ('failed', 'Başarısız'), ('delivered', 'Teslim Edildi')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='External message ID from provider', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.resident')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='notificatio_status_a242db_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_3db547_idx')],
            },
        ),
    ]
