# Generated by Django 5.2.13 on 2026-04-26 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationtemplate",
            options={
                "ordering": ["name"],
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
            },
        ),
    ]
