# Generated by Django 5.2.13 on 2026-04-25 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0004_alter_ownership_unique_together_and_more'),
        ('tickets', '0003_ticket_tickets_tic_apartme_54f61b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.OneToOneField(blank=True, help_text='Linked resident profile (null until registration approved)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Messenger User',
                'verbose_name_plural': 'Messenger Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (Resident → Bot)'), ('outbound', 'Outbound (CRM → Resident)'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('command', 'Command'), ('callback', 'Callback Query'), ('photo', 'Photo'), ('document', 'Document')], default='text', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_messages', to='tickets.ticket')),
                ('messenger_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.messengeruser')),
            ],
            options={
                'verbose_name': 'Bot Message',
                'verbose_name_plural': 'Bot Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('building_name', models.CharField(help_text='Building name as provided by resident', max_length=255)),
                ('apartment_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messenger_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to='messenger.messengeruser')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Request',
                'verbose_name_plural': 'Registration Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='messengeruser',
            index=models.Index(fields=['telegram_chat_id'], name='messenger_m_telegra_e37718_idx'),
        ),
        migrations.AddIndex(
            model_name='messengeruser',
            index=models.Index(fields=['resident'], name='messenger_m_residen_18411e_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessage',
            index=models.Index(fields=['messenger_user', '-created_at'], name='messenger_b_messeng_1a3c75_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessage',
            index=models.Index(fields=['ticket', '-created_at'], name='messenger_b_ticket__135205_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessage',
            index=models.Index(fields=['direction', 'message_type'], name='messenger_b_directi_d7e19f_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['status', '-created_at'], name='messenger_r_status_f1871b_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['phone'], name='messenger_r_phone_574e77_idx'),
        ),
    ]
