# Generated by Django 5.2.13 on 2026-04-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messengeruser",
            name="conversation_state",
            field=models.JSONField(
                blank=True, default=dict, help_text="Temporary state for multi-step bot conversations"
            ),
        ),
    ]
