# Generated by Django 5.2.13 on 2026-04-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0002_messengeruser_conversation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequest",
            name="role",
            field=models.CharField(
                choices=[("owner", "Mal Sahibi"), ("tenant", "Kiracı"), ("resident", "İkamet Eden")],
                default="owner",
                max_length=20,
            ),
        ),
    ]
