# Generated by Django 5.2.13 on 2026-04-26 15:53

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0003_registrationrequest_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messengeruser",
            name="conversation_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Temporary state for multi-step bot conversations",
                validators=[core.validators.validate_conversation_state],
            ),
        ),
    ]
