# Generated by Django 5.2.13 on 2026-04-26 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0004_alter_ownership_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ownership",
            options={"ordering": ["-created_at"], "verbose_name": "Ownership", "verbose_name_plural": "Ownerships"},
        ),
        migrations.AlterModelOptions(
            name="personalaccount",
            options={
                "ordering": ["account_number"],
                "verbose_name": "Personal Account",
                "verbose_name_plural": "Personal Accounts",
            },
        ),
    ]
