# Generated by Django 5.2.13 on 2026-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0005_add_model_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
