# Generated by Django 5.2.13 on 2026-05-02 19:25

from django.conf import settings
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0006_resident_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="tc_kimlik_no",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[common.validators.validate_tc_kimlik_no],
                verbose_name="TC Kimlik No",
            ),
        ),
        migrations.AddConstraint(
            model_name="resident",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tc_kimlik_no__gt", ""), ("tc_kimlik_no__isnull", False)),
                    models.Q(("passport_no__gt", ""), ("passport_no__isnull", False)),
                    _connector="OR",
                ),
                name="resident_has_at_least_one_id",
            ),
        ),
    ]
