# Generated by Django 5.2.13 on 2026-04-26 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"], "verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
