# Generated by Django 5.2.14 on 2026-05-07 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("payments", "Payments"),
                            ("aidat_charges", "Aidat Charges"),
                            ("meetings", "Meetings"),
                            ("residents", "Residents"),
                            ("apartments", "Apartments"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(choices=[("csv", "CSV"), ("xlsx", "Excel"), ("pdf", "PDF")], max_length=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/")),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Report",
                "verbose_name_plural": "Export Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
