# Generated by Django 5.2.13 on 2026-05-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время отправки напоминания жильцам",
                null=True,
                verbose_name="Напоминание отправлено",
            ),
        ),
    ]
