# Generated by Django 5.2.14 on 2026-05-10 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_meeting_reminder_sent_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetingprotocol",
            options={"ordering": ["-created_at"], "verbose_name": "Протокол", "verbose_name_plural": "Протоколы"},
        ),
    ]
